[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oof-tracker"
version = "0.1.0-alpha.1"
description = "A tool to track mistakes"
authors = [{name = "Your Name", email = "your.email@example.com"}]
dependencies = []
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
oof-tracker = "oof_tracker.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"